import { useMemo, useState } from "react";
import { Search, PackageSearch } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getItemIcon } from "@/lib/equipment-icons";
import { getSkillIcon } from "@/lib/skill-icons";
import { getItemSource, ITEM_SOURCE_NOTES, searchItemSources, type SourceTarget } from "@/lib/item-sources";

function TargetIcon({ target }: { target: SourceTarget }) { const src = target.type === "skill" ? getSkillIcon(target.name) : getItemIcon(target.name); return src ? <img src={src} alt="" className="h-8 w-8 object-contain" /> : <PackageSearch className="h-7 w-7 text-muted-foreground" />; }
export default function ItemSourcesPage() {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string | null>(null);
  const matches = useMemo(() => searchItemSources(query), [query]); const target = selected ? getItemSource(selected) : matches.length === 1 && normForSelection(query, matches[0].name) ? matches[0] : undefined;
  const grouped = useMemo(() => { if (!target) return []; const map = new Map<string, typeof target.sources>(); for (const source of target.sources) map.set(source.kind, [...(map.get(source.kind) || []), source]); return [...map.entries()]; }, [target]);
  return <main className="container mx-auto max-w-6xl space-y-6 px-4 py-8"><div><div className="flex items-center gap-2"><Search className="h-5 w-5 text-primary" /><h1 className="text-3xl font-semibold">Item &amp; Skill Sources</h1></div><p className="mt-2 text-muted-foreground">Search an item or skill to see where it can be obtained across Treasure lookup and the related game-data tabs.</p></div>
    <Card><CardContent className="space-y-3 pt-6"><label htmlFor="item-source-search" className="text-sm font-medium">Search item or skill</label><Input id="item-source-search" value={query} onChange={(event) => { setQuery(event.target.value); setSelected(null); }} placeholder="Try Pretty Cloth, Myriad Arrows, or Revive 50%" autoComplete="off" />{query && !target && <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{matches.map((match) => <button key={`${match.type}-${match.name}`} onClick={() => { setSelected(match.name); setQuery(match.name); }} className="flex items-center gap-3 rounded-md border p-3 text-left hover:bg-muted"><TargetIcon target={match} /><span><span className="block font-medium">{match.name}</span><span className="text-xs text-muted-foreground">{match.type} · {match.sources.length} sources</span></span></button>)}{matches.length === 0 && <p className="text-sm text-muted-foreground">No matching item or skill.</p>}</div>}</CardContent></Card>
    {target ? <div className="space-y-4"><Card><CardHeader className="flex-row items-center gap-3 space-y-0"><TargetIcon target={target} /><div><CardTitle>{target.name}</CardTitle><p className="text-sm text-muted-foreground">{target.type} · {target.sources.length} known sources</p></div></CardHeader></Card>{grouped.map(([kind, sources]) => <Card key={kind}><CardHeader><CardTitle className="text-lg">{kind}</CardTitle></CardHeader><CardContent className="space-y-3">{sources.map((source) => <div key={source.key} className="rounded-md border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{source.title}</span><Badge variant={source.confidence === "confirmed" ? "secondary" : "outline"}>{source.confidence}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{source.details}</p></div>)}</CardContent></Card>)}</div> : <Card><CardHeader><CardTitle>What is included</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground">{ITEM_SOURCE_NOTES.map((note) => <p key={note}>• {note}</p>)}</CardContent></Card>}</main>;
}
function normForSelection(query: string, name: string) { return query.trim() && query.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim() === name.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
